/**
 * Canonical Event Envelope V1.
 *
 * Hand-authored to mirror `schemas/events/event-envelope-v1.schema.json`
 * field-for-field. This file is NOT generated by
 * `scripts/generate_contracts.py` — the JSON Schema is the source of truth
 * for envelope shape, but a JSON Schema-to-TypeScript compiler is out of
 * scope for this workstream, so the interface below is kept in sync by hand
 * whenever the schema changes. Property order, names, and nullability match
 * the schema exactly; the schema itself carries no `description` fields, so
 * the comments below restate each field's role and JSON Schema constraint
 * from its name, `pattern`, and `required` membership rather than quoting
 * schema text that doesn't exist.
 *
 * Required schema properties (`required` array): id, name, occurredAt,
 * publishedAt, tenantId, producerNamespace, schemaVersion, classification,
 * data. Every other property has type `["string", "null"]` and is not
 * `required`, so it may be omitted entirely or present as `string | null`;
 * that is modeled here as an optional `string | null` field.
 */
export interface EventEnvelope<
	TData extends Record<string, unknown> = Record<string, unknown>,
> {
	/** Identity of the actor (user, service account, or system) that caused the event, if attributable. */
	actorId?: string | null;

	/** Id of the aggregate/entity this event is about, if the event has a single owning aggregate. */
	aggregateId?: string | null;

	/** Canonical capability id the event is attributed to, if any. Schema pattern: `^[a-z][a-z0-9-]*\.[a-z][a-z0-9-]*$`. */
	capabilityId?: string | null;

	/** Id of the event or command that directly caused this event, for causal chains. */
	causationId?: string | null;

	/** Data classification tag governing handling/retention of this event's payload. */
	classification: string;

	/** Correlation id linking this event to a broader request/operation chain. */
	correlationId?: string | null;

	/** Event-specific payload. Schema: `type: object` (unconstrained shape at the envelope level). */
	data: TData;
	/** Globally unique event identifier. Schema: `minLength: 12`, `maxLength: 64`. */
	id: string;

	/** Idempotency key of the operation that produced this event, if the operation was idempotency-guarded. */
	idempotencyKey?: string | null;

	/** Legal entity scope, when the event is scoped to one. */
	legalEntityId?: string | null;

	/** Location scope, when the event is scoped to one. */
	locationId?: string | null;

	/**
	 * Canonical event name. Schema pattern:
	 * `^[a-z][a-z0-9-]*\.[a-z][a-z0-9-]*\.[a-z][a-z0-9-]*\.v[1-9][0-9]*$`
	 * (`<namespace>.<entity>.<fact>.v<major>`), matching
	 * `@meridian/contracts-events`' `EventName`.
	 */
	name: string;

	/** When the fact this event describes actually occurred. Schema: `format: date-time`. */
	occurredAt: string;

	/** Organization scope within the tenant, when applicable. */
	organizationId?: string | null;

	/** Namespace of the producing domain/engine/platform service. Schema pattern: `^[a-z][a-z0-9-]*$`. */
	producerNamespace: string;

	/** When the event was published/emitted onto the bus. Schema: `format: date-time`. */
	publishedAt: string;

	/** Business or legal purpose the event's data may be used for, if constrained. */
	purpose?: string | null;

	/** Semantic version of the event's `data` payload shape. Schema pattern: `^\d+\.\d+\.\d+$`. */
	schemaVersion: string;

	/** Channel the triggering request arrived through (e.g. `web`, `native`, `api`, `job`), if applicable. */
	sourceChannel?: string | null;

	/** Tenant the event belongs to. Required on every event; never `null`. */
	tenantId: string;

	/** Distributed trace id, if tracing is active for the producing request. */
	traceId?: string | null;
}
