#!/usr/bin/env python3
"""Generate deterministic TypeScript contract packages from governed registries.

Mirrors the determinism, `--check` semantics, and stdlib-only constraints of
`scripts/generate_registries.py`: registries and the OpenAPI contract are the
single source of truth, and the generated TypeScript files under
`packages/contracts/*/src` are never hand-edited. The OpenAPI file is parsed
with the same line-oriented regex technique as
`scripts/validate_docs.py::collect_openapi_operations` so CI never grows a
YAML dependency.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]

GENERATED_HEADER = "// GENERATED by scripts/generate_contracts.py — DO NOT EDIT."

IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")

# Same extraction regexes as scripts/validate_docs.py::collect_openapi_operations,
# adapted to keep the original (non-normalized) OpenAPI path around for reuse.
OPENAPI_PATH = re.compile(r"^  (/[^:]+):\s*$")
OPENAPI_METHOD = re.compile(r"^    (get|post|put|patch|delete|options|head|trace):\s*$")
OPENAPI_OPERATION_ID = re.compile(r"^      operationId:\s*(\S+)\s*$")
OPENAPI_PERMISSION = re.compile(r"^      x-permission:\s*(\S+)\s*$")
OPENAPI_AUTHORIZATION = re.compile(r"^      x-authorization:\s*(\S+)\s*$")
OPENAPI_RESPONSE_STATUS = re.compile(r"^        ['\"]?(2\d\d)['\"]?:\s*$")
OPENAPI_ANY_RESPONSE = re.compile(r"^        (?:['\"]?\d{3}['\"]?|default):\s*$")
OPENAPI_REF = re.compile(r"\$ref:\s*['\"]([^'\"]+)['\"]")

HTTP_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD", "TRACE"]


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def ts_string(value: str) -> str:
    return json.dumps(value)


def ts_key(key: str) -> str:
    return key if IDENTIFIER.fullmatch(key) else ts_string(key)


# ---------------------------------------------------------------------------
# Capabilities
# ---------------------------------------------------------------------------


def load_capability_ids() -> list[str]:
    data = load_json(ROOT / "registry" / "capabilities.json")
    return sorted(str(item["id"]) for item in data["capabilities"])


def render_capabilities_index(capability_ids: list[str]) -> str:
    lines: list[str] = [
        GENERATED_HEADER,
        "// Source: registry/capabilities.json",
        "",
        "export const CAPABILITY_IDS = [",
    ]
    for capability_id in capability_ids:
        lines.append(f"\t{ts_string(capability_id)},")
    lines.append("] as const;")
    lines.append("")
    lines.append("export type CapabilityId = (typeof CAPABILITY_IDS)[number];")
    lines.append("")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Permissions
# ---------------------------------------------------------------------------


def load_permission_ids() -> list[str]:
    data = load_json(ROOT / "registry" / "permissions.json")
    return sorted(str(item["id"]) for item in data["permissions"])


def load_permissions_by_namespace() -> dict[str, list[str]]:
    data = load_json(ROOT / "registry" / "permissions.json")
    grouped: dict[str, list[str]] = {}
    for item in data["permissions"]:
        grouped.setdefault(str(item["namespace"]), []).append(str(item["id"]))
    for namespace in grouped:
        grouped[namespace].sort()
    return dict(sorted(grouped.items()))


def render_permissions_index(permission_ids: list[str], grouped: dict[str, list[str]]) -> str:
    lines: list[str] = [
        GENERATED_HEADER,
        "// Source: registry/permissions.json",
        "",
        "export const PERMISSION_IDS = [",
    ]
    for permission_id in permission_ids:
        lines.append(f"\t{ts_string(permission_id)},")
    lines.append("] as const;")
    lines.append("")
    lines.append("export type PermissionId = (typeof PERMISSION_IDS)[number];")
    lines.append("")
    lines.append("export const PERMISSIONS_BY_NAMESPACE = {")
    for namespace, ids in grouped.items():
        lines.append(f"\t{ts_key(namespace)}: [")
        for permission_id in ids:
            lines.append(f"\t\t{ts_string(permission_id)},")
        lines.append("\t],")
    lines.append("} as const satisfies Record<string, readonly PermissionId[]>;")
    lines.append("")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Events
# ---------------------------------------------------------------------------


def load_events() -> tuple[list[str], dict[str, str]]:
    data = load_json(ROOT / "registry" / "events.json")
    names = sorted(str(item["name"]) for item in data["events"])
    owners = {str(item["name"]): str(item["owner"]) for item in data["events"]}
    return names, owners


def render_events_index(event_names: list[str], owners: dict[str, str]) -> str:
    lines: list[str] = [
        GENERATED_HEADER,
        "// Source: registry/events.json",
        "",
        "export const EVENT_NAMES = [",
    ]
    for name in event_names:
        lines.append(f"\t{ts_string(name)},")
    lines.append("] as const;")
    lines.append("")
    lines.append("export type EventName = (typeof EVENT_NAMES)[number];")
    lines.append("")
    lines.append("export const EVENT_OWNERS: Record<EventName, string> = {")
    for name in event_names:
        lines.append(f"\t{ts_string(name)}: {ts_string(owners[name])},")
    lines.append("};")
    lines.append("")
    lines.append('export type { EventEnvelope } from "./envelope";')
    lines.append("")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# API / endpoints
# ---------------------------------------------------------------------------


def normalize_endpoint_path(route: str) -> str:
    """Normalize base-version and placeholder names for contract parity checks.

    Kept identical to scripts/validate_docs.py::normalize_endpoint_path so the
    generator's join agrees with the governance validator's join.
    """
    if route.startswith("/v1/"):
        route = route[3:]
    return re.sub(r"\{[^{}]+\}", "{}", route)


def collect_openapi_operations(path: Path) -> dict[tuple[str, str], dict[str, str]]:
    """Extract the controlled OpenAPI path surface without adding a YAML dependency.

    Adapted from scripts/validate_docs.py::collect_openapi_operations. Keys are
    (METHOD, normalized-path); values carry the operationId/permission/authorization
    plus the original (non-normalized) OpenAPI path for diagnostics.
    """
    operations: dict[tuple[str, str], dict[str, str]] = {}
    current_path: str | None = None
    current_key: tuple[str, str] | None = None
    current_section: str | None = None
    current_response_status: str | None = None
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        path_match = OPENAPI_PATH.match(line)
        if path_match:
            current_path = path_match.group(1)
            current_key = None
            current_section = None
            current_response_status = None
            continue
        method_match = OPENAPI_METHOD.match(line)
        if method_match and current_path:
            current_key = (method_match.group(1).upper(), normalize_endpoint_path(current_path))
            if current_key in operations:
                raise ValueError(
                    f"{path.relative_to(ROOT)}:{line_number}: duplicate OpenAPI operation "
                    f"{current_key[0]} {current_path}"
                )
            operations[current_key] = {"source_line": str(line_number), "openapi_path": current_path}
            current_section = None
            current_response_status = None
            continue
        if current_key is None:
            continue
        if line == "      requestBody:":
            current_section = "request"
            current_response_status = None
            continue
        if line == "      responses:":
            current_section = "responses"
            current_response_status = None
            continue
        if line.startswith("      ") and not line.startswith("        "):
            current_section = None
            current_response_status = None
        for field, pattern in (
            ("operation_id", OPENAPI_OPERATION_ID),
            ("permission", OPENAPI_PERMISSION),
            ("authorization", OPENAPI_AUTHORIZATION),
        ):
            match = pattern.match(line)
            if match:
                operations[current_key][field] = match.group(1)
                break
        if current_section == "responses":
            status_match = OPENAPI_RESPONSE_STATUS.match(line)
            if status_match:
                current_response_status = status_match.group(1)
                if "success_status" not in operations[current_key]:
                    operations[current_key]["success_status"] = current_response_status
                continue
            if OPENAPI_ANY_RESPONSE.match(line):
                current_response_status = None
                continue
        ref_match = OPENAPI_REF.search(line)
        if not ref_match:
            continue
        if current_section == "request" and "request_ref" not in operations[current_key]:
            operations[current_key]["request_ref"] = ref_match.group(1)
        elif (
            current_section == "responses"
            and current_response_status == operations[current_key].get("success_status")
            and "response_ref" not in operations[current_key]
        ):
            operations[current_key]["response_ref"] = ref_match.group(1)
    return operations


def build_endpoints() -> tuple[list[dict[str, Any]], int, int]:
    manifest = load_json(ROOT / "registry" / "endpoint-permissions.json").get("endpoints", [])
    operations = collect_openapi_operations(ROOT / "openapi" / "first-slice-v1.yaml")

    manifest_keys: set[tuple[str, str]] = set()
    rows: list[dict[str, Any]] = []
    for item in manifest:
        method = str(item["method"]).upper()
        route = str(item["path"])
        key = (method, normalize_endpoint_path(route))
        if key in manifest_keys:
            raise ValueError(f"registry/endpoint-permissions.json: duplicate endpoint {method} {route}")
        manifest_keys.add(key)
        operation = operations.get(key)
        if operation is None or not operation.get("operation_id"):
            raise ValueError(
                f"registry/endpoint-permissions.json: no OpenAPI operationId found for {method} {route}"
            )
        row: dict[str, Any] = {
            "method": method,
            "path": route,
            "operationId": operation["operation_id"],
            "successStatus": int(operation.get("success_status", "200")),
        }
        if operation.get("request_ref"):
            row["requestRef"] = operation["request_ref"]
        if operation.get("response_ref"):
            row["responseRef"] = operation["response_ref"]
        if item.get("permission"):
            row["permission"] = str(item["permission"])
        if item.get("authorization"):
            row["authorization"] = str(item["authorization"])
        rows.append(row)

    openapi_keys = set(operations)
    missing_from_openapi = sorted(f"{m} {p}" for m, p in (manifest_keys - openapi_keys))
    missing_from_manifest = sorted(f"{m} {p}" for m, p in (openapi_keys - manifest_keys))
    if missing_from_openapi or missing_from_manifest:
        raise ValueError(
            "endpoint parity mismatch between registry/endpoint-permissions.json and "
            "openapi/first-slice-v1.yaml: "
            f"missing from OpenAPI: {missing_from_openapi}; "
            f"missing from manifest: {missing_from_manifest}"
        )

    rows.sort(key=lambda item: (item["path"], item["method"]))
    return rows, len(manifest_keys), len(openapi_keys)


def render_api_index(rows: list[dict[str, Any]], permission_ids: list[str]) -> str:
    lines: list[str] = [
        GENERATED_HEADER,
        "// Source: registry/endpoint-permissions.json + openapi/first-slice-v1.yaml",
        "//",
        "// registry/architecture-rules.json restricts the \"contracts\" package family",
        "// to depend only on \"foundation\" (no intra-family dependency is allowed, per",
        "// docs/blueprint/14-Engineering/ARCHITECTURE_DEPENDENCY_RULES.md §Contracts).",
        "// packages/contracts/api therefore cannot import PermissionId from",
        "// @meridian/contracts-permissions; the permission id union is regenerated and",
        "// inlined here from the same source of truth (registry/permissions.json).",
        "",
        "export const KNOWN_PERMISSION_IDS = [",
    ]
    for permission_id in permission_ids:
        lines.append(f"\t{ts_string(permission_id)},")
    lines.append("] as const;")
    lines.append("")
    lines.append("export type PermissionId = (typeof KNOWN_PERMISSION_IDS)[number];")
    lines.append("")
    lines.append('export type Authorization = "authenticated_session" | "authenticated_membership";')
    lines.append("")
    method_union = " | ".join(ts_string(method) for method in HTTP_METHODS)
    lines.append("export interface EndpointDefinition {")
    lines.append("\tauthorization?: Authorization;")
    lines.append(f"\tmethod: {method_union};")
    lines.append("\toperationId: string;")
    lines.append("\tpath: string;")
    lines.append("\tpermission?: PermissionId;")
    lines.append("}")
    lines.append("")
    lines.append("export const ENDPOINTS = [")
    for row in rows:
        # Property order matches Biome's assist/source/useSortedKeys (alphabetical
        # object-literal keys), so the generator's output is already lint-clean.
        parts = []
        if "authorization" in row:
            parts.append(f"authorization: {ts_string(row['authorization'])}")
        parts.append(f"method: {ts_string(row['method'])}")
        parts.append(f"operationId: {ts_string(row['operationId'])}")
        parts.append(f"path: {ts_string(row['path'])}")
        if "permission" in row:
            parts.append(f"permission: {ts_string(row['permission'])}")
        lines.append(f"\t{{ {', '.join(parts)} }},")
    lines.append("] as const satisfies readonly EndpointDefinition[];")
    lines.append("")
    lines.append("export type Endpoint = (typeof ENDPOINTS)[number];")
    lines.append("")
    lines.append("export type EndpointsByPermission = {")
    lines.append("\t[Permission in PermissionId]: Extract<Endpoint, { permission: Permission }>;")
    lines.append("};")
    lines.append("")
    lines.append("export type EndpointsByOperationId = {")
    lines.append('\t[Id in Endpoint["operationId"]]: Extract<Endpoint, { operationId: Id }>;')
    lines.append("};")
    lines.append("")
    return "\n".join(lines) + "\n"


def render_platform_api_metadata(rows: list[dict[str, Any]]) -> str:
    lines = [
        GENERATED_HEADER,
        "// Source: openapi/first-slice-v1.yaml + registry/endpoint-permissions.json",
        "",
        "export const OPENAPI_OPERATION_METADATA = [",
    ]
    for row in rows:
        parts = []
        for key in (
            "authorization",
            "method",
            "operationId",
            "path",
            "permission",
            "requestRef",
            "responseRef",
            "successStatus",
        ):
            if key not in row:
                continue
            value = row[key]
            rendered = str(value) if isinstance(value, int) else ts_string(value)
            parts.append(f"{key}: {rendered}")
        lines.append(f"\t{{ {', '.join(parts)} }},")
    lines.extend(
        [
            "] as const;",
            "",
            "export type OpenApiOperationMetadata =",
            "\t(typeof OPENAPI_OPERATION_METADATA)[number];",
            "",
        ]
    )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Biome formatting
# ---------------------------------------------------------------------------


def find_biome_binary() -> Path | None:
    name = "biome.exe" if sys.platform == "win32" else "biome"
    candidate = ROOT / "node_modules" / ".bin" / name
    return candidate if candidate.exists() else None


def biome_format(target_dir: Path, content: str) -> str:
    """Format generated TypeScript with the repository's own Biome config.

    `bunx ultracite check packages/contracts` lints these generated files like
    any other TypeScript source (root `check` only excludes `apps`/`packages`
    from *outside* those directories, not generated files within them), so the
    committed output must already match what Biome's formatter produces.
    Rather than hand-reimplementing Biome's line-wrapping rules in Python, the
    repository's own pinned `biome` binary formats a scratch copy of the file
    (kept inside `target_dir` so Biome's upward config resolution still finds
    the root `biome.json`) and the formatted bytes are read back.
    """
    binary = find_biome_binary()
    if binary is None:
        print(
            "warning: node_modules/.bin/biome not found; run `bun install` first. "
            "Emitting unformatted TypeScript.",
            file=sys.stderr,
        )
        return content
    fd, tmp_name = tempfile.mkstemp(dir=target_dir, prefix=".generate_contracts_fmt_", suffix=".ts")
    tmp_path = Path(tmp_name)
    try:
        with open(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        result = subprocess.run(
            [str(binary), "format", "--write", str(tmp_path)],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            raise ValueError(
                f"biome format failed for scratch copy of a generated contract file: "
                f"{result.stdout}\n{result.stderr}"
            )
        return tmp_path.read_text(encoding="utf-8")
    finally:
        tmp_path.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check and not path.parent.is_dir():
        print(f"stale contract: {path.relative_to(ROOT).as_posix()} (package directory missing)", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    formatted = biome_format(path.parent, content)
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != formatted:
            print(f"stale contract: {path.relative_to(ROOT).as_posix()}", file=sys.stderr)
            return False
        return True
    path.write_text(formatted, encoding="utf-8", newline="\n")
    print(f"wrote {path.relative_to(ROOT).as_posix()}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    try:
        capability_ids = load_capability_ids()
        permission_ids = load_permission_ids()
        permissions_by_namespace = load_permissions_by_namespace()
        event_names, event_owners = load_events()
        endpoint_rows, manifest_count, openapi_count = build_endpoints()
    except (OSError, ValueError, KeyError, json.JSONDecodeError) as exc:
        print(f"contract generation failed: {exc}", file=sys.stderr)
        return 1

    print(
        f"joined {len(endpoint_rows)} endpoints "
        f"(manifest {manifest_count} / openapi {openapi_count}); "
        f"{len(capability_ids)} capabilities; {len(permission_ids)} permissions; "
        f"{len(event_names)} events",
        file=sys.stderr,
    )

    outputs = {
        ROOT / "packages" / "contracts" / "capabilities" / "src" / "index.ts": render_capabilities_index(
            capability_ids
        ),
        ROOT / "packages" / "contracts" / "permissions" / "src" / "index.ts": render_permissions_index(
            permission_ids, permissions_by_namespace
        ),
        ROOT / "packages" / "contracts" / "events" / "src" / "index.ts": render_events_index(
            event_names, event_owners
        ),
        ROOT / "packages" / "contracts" / "api" / "src" / "index.ts": render_api_index(
            endpoint_rows, permission_ids
        ),
        ROOT / "packages" / "contracts" / "platform-api" / "src" / "generated.ts": render_platform_api_metadata(
            endpoint_rows
        ),
    }

    ok = True
    for path, content in outputs.items():
        ok &= write_or_check(path, content, args.check)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
