/**
 * Opaque internal identifiers, distinct from human-readable references.
 *
 * CLAUDE.md §7 "Money, Time, Quantity, and Identity": "Use opaque internal
 * identifiers separately from human references." This module provides:
 *
 * - {@link Id}: a branded, generated, non-guessable internal identifier
 *   (UUIDv7) meant for storage keys, foreign keys, and cross-service
 *   references. It carries no business meaning.
 * - {@link HumanRef}: a branded type for human-facing references (invoice
 *   numbers, receipt numbers, order codes) that are meaningful to a person
 *   and are never used as the opaque identifier for a record.
 *
 * The two brands are structurally incompatible: a value typed `Id<"Invoice">`
 * cannot be assigned to a parameter typed `HumanRef<"Invoice">` or vice versa,
 * even though both are strings at runtime. See `id.types.test.ts` for
 * compile-time proof of this separation.
 */

const HEX_CHARS = "0123456789abcdef";

/**
 * A branded opaque internal identifier. `TBrand` is a string literal
 * (typically the entity name, e.g. `"Invoice"`) used purely at the type
 * level to prevent mixing identifiers from different entities; it has no
 * runtime representation.
 */
export type Id<TBrand extends string> = string & { readonly __brand: TBrand };

/**
 * A branded human-readable reference (invoice number, receipt number, order
 * code, etc.). Per CLAUDE.md §7, human references are a distinct concept from
 * opaque internal identifiers ({@link Id}) and the two are never
 * interchangeable, even when both happen to be strings.
 */
export type HumanRef<TBrand extends string> = string & {
	readonly __humanRef: TBrand;
};

/**
 * Brand an already-formatted human-readable reference. This performs no
 * validation beyond non-emptiness because human reference formats are
 * domain-specific (invoice numbering schemes, receipt formats, etc.) and are
 * defined by the owning domain, not by Foundation.
 */
export function toHumanRef<TBrand extends string>(
	value: string
): HumanRef<TBrand> {
	if (value.length === 0) {
		throw new TypeError("HumanRef value must not be empty");
	}
	return value as HumanRef<TBrand>;
}

const UUID_PATTERN =
	/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Structural check for "is this string shaped like a UUID". Does not verify
 * the UUID version/variant bits, since {@link Id} accepts any RFC 4122-shaped
 * UUID (a stored `Id` may have been generated by an older version scheme).
 */
export function isId<TBrand extends string>(
	value: string
): value is Id<TBrand> {
	return UUID_PATTERN.test(value);
}

/**
 * Parse and brand a string as an {@link Id}, validating UUID shape.
 */
export function parseId<TBrand extends string>(
	value: string
): Id<TBrand> | undefined {
	return isId<TBrand>(value) ? value : undefined;
}

// Module-scoped state for the UUIDv7 monotonic random counter. Per the
// UUIDv7 draft's "Monotonic Random" method: within the same millisecond,
// increment a random-seeded counter instead of drawing fresh random bits, so
// identifiers generated in rapid succession remain lexicographically sorted.
let lastTimestampMs = -1;
let counter = 0;

const COUNTER_BITS = 12;
const COUNTER_MAX = 2 ** COUNTER_BITS - 1;

const COUNTER_MODULUS = COUNTER_MAX + 1;

function randomCounterSeed(): number {
	const bytes = new Uint8Array(2);
	crypto.getRandomValues(bytes);
	// 12-bit seed, matching the rand_a field width, built with arithmetic
	// (not bitwise shift/mask operators, which this codebase's lint config
	// prohibits): high byte * 256 + low byte reconstructs the 16-bit value,
	// then `% COUNTER_MODULUS` restricts it to 12 bits. The `?? 0` fallbacks
	// are unreachable in practice (bytes always has exactly 2 elements) and
	// exist only to satisfy noUncheckedIndexedAccess.
	const value = (bytes[0] ?? 0) * 256 + (bytes[1] ?? 0);
	return value % COUNTER_MODULUS;
}

function nextTimestampAndCounter(nowMs: number): {
	timestampMs: number;
	counterValue: number;
} {
	if (nowMs > lastTimestampMs) {
		lastTimestampMs = nowMs;
		counter = randomCounterSeed();
		return { counterValue: counter, timestampMs: nowMs };
	}

	// Same (or, on a clock rewind, earlier) millisecond as the previous call:
	// advance the counter to preserve monotonic ordering.
	counter += 1;
	if (counter > COUNTER_MAX) {
		// Counter exhausted within this millisecond: borrow a millisecond so
		// ordering is preserved instead of wrapping and going non-monotonic.
		lastTimestampMs += 1;
		counter = 0;
	}
	return { counterValue: counter, timestampMs: lastTimestampMs };
}

function toHex(byte: number): string {
	// Arithmetic (not bitwise) nibble split: high nibble via floor-divide by
	// 16, low nibble via remainder. The `?? "0"` fallbacks are unreachable
	// (HEX_CHARS has all 16 hex digits and both operands are always in
	// 0-15) and exist only to satisfy noUncheckedIndexedAccess.
	const high = HEX_CHARS[Math.floor(byte / 16) % 16] ?? "0";
	const low = HEX_CHARS[byte % 16] ?? "0";
	return high + low;
}

/**
 * Generate a new UUIDv7 (RFC 9562), branded as `Id<TBrand>`.
 *
 * UUIDv7 embeds a 48-bit millisecond Unix timestamp in the leading bits, so
 * generated identifiers sort chronologically — useful for primary keys and
 * index locality — while still being globally unique and non-sequential
 * within a millisecond (unlike a raw auto-increment integer, they do not leak
 * record counts or ordering to a human reference, satisfying the "opaque"
 * half of CLAUDE.md §7's identifier rule).
 *
 * Implemented from scratch with `crypto.getRandomValues` (a standard Web
 * Crypto API present in Bun, Node ≥19, and browsers — not a Bun-specific
 * global) rather than `crypto.randomUUID()`, because `randomUUID()` only
 * produces UUIDv4 and cannot be parameterized to produce UUIDv7.
 */
export function newId<TBrand extends string>(): Id<TBrand> {
	const nowMs = Date.now();
	const { timestampMs, counterValue } = nextTimestampAndCounter(nowMs);

	// 6 bytes: 48-bit big-endian millisecond timestamp.
	const tsBytes = new Uint8Array(6);
	let remaining = timestampMs;
	for (let i = 5; i >= 0; i -= 1) {
		tsBytes[i] = remaining % 256;
		remaining = Math.floor(remaining / 256);
	}

	// rand_a (12 bits): the monotonic counter, prefixed with version nibble 7.
	// counterValue is 0-4095 (12 bits): dividing by 256 yields its top 4 bits
	// (0-15) with no overlap against the 0x70 version nibble, so addition
	// stands in for the bitwise OR a shift/mask implementation would use.
	const randABytes = new Uint8Array(2);
	randABytes[0] = 0x70 + Math.floor(counterValue / 256);
	randABytes[1] = counterValue % 256;

	// rand_b (62 bits): fresh cryptographic randomness, with the variant bits
	// (10) forced into the top two bits of the first byte. Keeping the low 6
	// bits (value % 64) and adding 128 sets those two top bits without
	// touching the rest, again avoiding a bitwise mask/OR.
	const randBBytes = new Uint8Array(8);
	crypto.getRandomValues(randBBytes);
	randBBytes[0] = ((randBBytes[0] ?? 0) % 64) + 128;

	const hex =
		Array.from(tsBytes, toHex).join("") +
		Array.from(randABytes, toHex).join("") +
		Array.from(randBBytes, toHex).join("");

	const uuid = `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20, 32)}`;
	return uuid as Id<TBrand>;
}
